dataset:
  batch_size: 8 # extract features 
  clip_duration: 4.0
  crop_size: 112
  video_fps: 8.0
  audio_clip_duration: 4.0
  audio_fps: 16000.
  hop_length: 143                 # this is equal to 0.01 sec / 10 ms
  audio_fps_out: 112              # when hop length is 10 ms, audio_fps_out = 112; to match with ?x16 patch
  n_mels: 80                      # ignore this for log-spectrogram
  n_fft: 1024
  fold: 1
  name: kinetics_sound
  return_video: true
  return_audio: true
  test:
    aug_mode: val
    clips_per_video: 2
    mode: video
    split: val
    aud_aug_kwargs:
        normalize: true
        trim_pad: true    
    vid_aug_kwargs:
      normalize: true
      pad_missing: true
      totensor: true
  train:
    aug_mode: train
    clips_per_video: 20 # size of 10 epochs
    mode: clip 
    split: train
    aud_aug_kwargs: # ** VJ-MASK-RC-TW **
        vol: 0.1
        fmask_len: [0, 10]
        tmask_len: [0, 20]
        num_fmask: 2
        num_tmask: 2
        wrap_window: 20
        voljitter: true
        timewarp: false
        fmask: false
        tmask: false
        randcrop: false
        normalize: true
        trim_pad: true
    vid_aug_kwargs: # ** MSC-HF-CJ-GS-CO **
        color: [0.4, 0.4, 0.4, 0.2]
        min_area: [0.08, 1]
        cutout_size: 0 
        num_of_cutout: 0
        p_flip: 0.5
        p_gray: 0.2
        p_blur: 0.0 # don't apply gaussian-blur in fixedfeat
        p_cutout: 0.0 # not applying cutout
        pad_missing: true
        normalize: true
        totensor: true    
  aud_transform: "strong"
  vid_transform: "strong3crop"
model:
  apply_l2: true
  apply_bn: false
  feat_dim: 768 # for vit base
  svm:
      cost: [0.00001, 0.0001, 0.001, 0.01, 0.1, 1] # 0.0001
      iter: 1000
      scale_features: false
  vid_backbone: # configurations are based on the pretraining
      frame_size: [3, 112, 112]
      num_frames: 32
      patch_spatial: [16, 16]
      patch_temporal: 4
      apply_cls_token: true 
      vit_config: "base" 
  aud_backbone: # configurations are based on the pretraining
      spec_size: [80, 448] 
      patch_spatial: [4, 16]
      apply_cls_token: true 
      vit_config: "base"
  fwd_kwargs:
      feat_op: 'pool'
name: kinetics_sound-svm
num_workers: 10
progress:
  log2tb: false
  print_freq: 10
  wandb: true
# best