apex: true
apex_opt_level: O1
dataset:
  aud_transform: strong
  audio_clip_duration: 4
  audio_fps: 16000.0
  audio_fps_out: 112
  batch_size: 256
  fold: 1
  hop_length: 143
  n_fft: 1024
  n_mels: 80
  name: fsd50
  test:
    aud_aug_kwargs:
      DB_NORM: _KINETICS
      normalize: true
      trim_pad: true
    aug_mode: val
    clips_per_video: 8
    drop_last: false
    ensemble: mean
    mode: video
    split: test
    use_shuffle: false
  train:
    aud_aug_kwargs:
      DB_NORM: _KINETICS
      fmask: false
      fmask_len:
      - 0
      - 0
      normalize: true
      num_fmask: 0
      num_tmask: 0
      randcrop: false
      timewarp: false
      tmask: false
      tmask_len:
      - 0
      - 0
      trim_pad: true
      vol: 0.1
      voljitter: true
      wrap_window: 0
    aug_mode: train
    clips_per_video: 10
    drop_last: true
    mode: clip
    split: train
    use_shuffle: true
hyperparams:
  lr:
    base_lr: 0.001
    final_lr: 1.0e-06
    name: fixed
    warmup_epochs: 5 # ignored
    warmup_lr: 1.0e-06 # ignored
    milestones: [10, 30] # ignored
    gamma: 0.1 # ignored
  num_epochs: 50
  optimizer:
    betas:
    - 0.9
    - 0.999
    momentum: 0.9
    name: adamw
    weight_decay: 0.00001
model:
  backbone:
    apply_cls_token: true
    patch_spatial:
    - 4
    - 16
    spec_size:
    - 80
    - 448
    vit_config: base
  classifier:
    num_classes: 200
    use_bn: false
    l2_norm: false
    use_dropout: true
    dropout: 0.3
  fwd_kwargs:
    feat_op: pool
name: fsd50-linear
num_workers: 20
progress:
  log2tb: false
  print_freq: 10
  wandb: false
sync_bn: false
