apex: true
apex_opt_level: O1
dataset:
  aud_transform: strong
  audio_clip_duration: 4
  audio_fps: 16000.0
  audio_fps_out: 112
  batch_size: 128
  fold: 1
  hop_length: 143
  n_fft: 1024
  n_mels: 80
  name: fsd50
  test:
    aud_aug_kwargs:
      DB_NORM: _KINETICS
      normalize: true
      trim_pad: true
    aug_mode: val
    clips_per_video: 8
    drop_last: false
    ensemble: mean
    mode: video
    split: test
    use_shuffle: false
  train:
    aud_aug_kwargs:
      DB_NORM: _KINETICS
      fmask: true
      fmask_len:
      - 0
      - 10
      normalize: true
      num_fmask: 2
      num_tmask: 2
      randcrop: true
      timewarp: true
      tmask: true
      tmask_len:
      - 0
      - 20
      trim_pad: true
      vol: 0.2
      voljitter: true
      wrap_window: 20
    aug_mode: train
    clips_per_video: 1
    drop_last: true
    mode: clip
    split: train
    use_shuffle: true
eval_freq: 1
hyperparams:
  layer_decay: 0.65
  lr:
    base_lr: 0.0001
    final_lr: 0.0
    gamma: 0.1
    milestones:
    - 10
    - 30
    name: fixed
    warmup_epochs: 5
    warmup_lr: 1.0e-06
  num_epochs: 30 # 100 it worse after this point
  optimizer:
    betas:
    - 0.9
    - 0.999
    momentum: 0.9
    name: adamw
    weight_decay: 1.0e-05
model:
  backbone:
    apply_cls_token: true
    drop_path_rate: 0
    drop_rate: 0
    patch_spatial:
    - 4
    - 16
    spec_size:
    - 80
    - 448
    vit_config: base
  classifier:
    dropout: 0.3
    l2_norm: false
    num_classes: 200
    use_bn: false
    use_dropout: true
  fwd_kwargs:
    feat_op: pool
name: fsd50-linear
num_workers: 20
progress:
  log2tb: false
  print_freq: 10
  wandb: false
sync_bn: false