dataset:
  batch_size: 32 # extract features 
  audio_clip_duration: 4
  audio_fps: 16000.
  hop_length: 143                 # this is equal to 0.01 sec / 10 ms
  audio_fps_out: 112              # when hop length is 10 ms, audio_fps_out = 112; to match with ?x16 patch
  n_mels: 80                      # ignore this for log-spectrogram
  n_fft: 1024
  fold: 1
  name: esc50
  test:
    aug_mode: val
    clips_per_video: 3
    mode: video
    split: test-{fold:01d}
    aud_aug_kwargs:
        normalize: true
        trim_pad: true    
        DB_NORM: '_KINETICS'
  train:
    aug_mode: train
    clips_per_video: 100 # size of 10 epochs
    mode: clip 
    split: train-{fold:01d}
    aud_aug_kwargs: # ** VJ-MASK-RC-TW **
        vol: 0.1
        fmask_len: [0, 10]
        tmask_len: [0, 20]
        num_fmask: 2
        num_tmask: 2
        wrap_window: 20
        voljitter: true
        timewarp: false
        fmask: false
        tmask: false
        randcrop: false
        normalize: true
        trim_pad: true
        DB_NORM: '_KINETICS'
  aud_transform: "strong"
model:
  svm:
      cost: [0.00001, 0.0001, 0.001, 0.01, 0.1, 1] # 0.0001
      iter: 1000
      scale_features: false
  backbone: # configurations are based on the pretraining
      spec_size: [80, 448] 
      patch_spatial: [4, 16]
      apply_cls_token: true 
      vit_config: "base"
  fwd_kwargs:
      feat_op: 'pool'
name: esc50-svm
num_workers: 10
progress:
  log2tb: false
  print_freq: 10
  wandb: true
# best